field_name = {
    ('!'..'9' | ';'..'~')+
}

field_value = {
    (' '..'~')*
}

comment = {
    "#" ~ field_value ~ "\n"
}

field = {
    field_name ~
    ":" ~
    field_value? ~
    (
      "\n" ~
      ((" " ~ field_value) | comment)
    )* ~
    "\n"?
}

paragraph = {
    (comment | field)+
}

single_paragraph = {
    SOI ~ paragraph ~ "\n"* ~ EOI
}

multiple_paragraphs = {
    SOI ~ ((paragraph | comment)* ~ "\n"* ~ EOI)
}
