on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-test.yml
  pull_request:
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-test.yml
  workflow_dispatch:
permissions: read-all
name: cargo test
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags: [
          "",
          "--all-features",
          "--no-default-features --features ''",
          "--no-default-features --features 'serde'",
          "--no-default-features --features 'sequoia'",
          "--no-default-features --features 'chrono'",
          "--no-default-features --features 'tokio'",
          "--no-default-features --features 'hex'"
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            clang \
            llvm \
            nettle-dev
        shell: bash
      - name: cargo test
        shell: bash
        run: |
          cargo test ${{ matrix.flags }}
