on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-build.yml
  pull_request:
    paths:
      - "**.rs"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-build.yml
permissions: read-all
name: cargo build
jobs:
  cargobuild:
    name: cargo build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags: [
          "",
          "--all-features",
          "--no-default-features --features ''",
          "--no-default-features --features 'sequoia'",
          "--no-default-features --features 'serde'",
          "--no-default-features --features 'chrono'",
          "--no-default-features --features 'tokio'",
          "--no-default-features --features 'hex'"
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run cargo build
        run: |
          cargo build ${{ matrix.flags }}
        shell: bash
